# Generated by Django 6.0 on 2026-01-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0004_rename_image_post_photo_category_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='freelance.tag'),
        ),
    ]
