# Generated by Django 6.0 on 2026-01-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0005_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
